language: csharp
solution: Net.Bluewalk.DotNetEnvironmentExtensions.sln
mono: none
dotnet: 3.0.100

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1

script:
 - dotnet restore
 - dotnet build -c Release

deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push Net.Bluewalk.DotNetEnvironmentExtensions/bin/Release/Net.Bluewalk.DotNetEnvironmentExtensions.*.nupkg --api-key $NUGET_API_KEY --source $NUGET_SOURCE
  on:
    branch: master
    condition: '"x${NUGET_API_KEY}" != "x" && "x$NUGET_SOURCE" != "x"'
